# [Info]
site_name: 零式岚的笔记本
site_url: https://note.flyburg.cc/
site_description: 零式岚的笔记本

# [UI]
## [top]
theme:
  name: material
  custom_dir: overrides
  favicon: https://s2.loli.net/2025/01/27/oFMcIOLbZstxUjH.png
  font:
    text: LXGW WenKai Screen
    code: Maple Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/auto-fix
        name: 切换至日间模式
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: var(--md-primary-fg-color)
      toggle:
        icon: material/toggle-switch
        name: 切换至夜间模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: var(--md-primary-fg-color)
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至跟随系统模式
  features:
    - announce.dismiss
    - navigation.tracking   #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    # - navigation.footer # 底部的翻页
    # - navigation.expand # 打开Tab时左侧目录全部展开
    # - toc.follow
    - search.share   #搜索分享按钮
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
    logo: material/notebook
edit_uri: edit/main/docs # 编辑按钮跳转的链接

## [top-right corner]
repo_url: https://github.com/Fanovian/notebook # 右上角的GitHub链接
repo_name: Fanovian's Notebook # 鼠标悬浮提示

## [bottom-left corner]
copyright: Copyright &copy; 2023 - 2025 Fanovian

## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/solid/blog
      link: https://blog.flyburg.cc/
      name: Blog
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/85414704
      name: Bilibili # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/flyburg
      name: GitHub | Flyburg
    - icon: material/email
      link: mailto:<flyburg@outlook.com>
      name: Email

# [Extensions]
plugins:
  - search:
      separator: '[\s\u200b\-]'
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  - statistics:
      page_check_metadata: comments
      exclude_path: about/
  - add-number:
      strict_mode: False
      order: 2
      excludes: 
        - course/ads/
        - course/fds/
        - course/ai/
        - course/arch/
        - self/html/

markdown_extensions:
  # - abbr
  - meta
  - def_list
  - attr_list
  # - admonition
  # - footnotes
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # - pymdownx.caret
  - pymdownx.critic
  # - pymdownx.betterem
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.inlinehilite
  # - markdown.extensions.attr_list
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 4  # 将深度从 4 改为 2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/mathjax.js
  - javascripts/article-cards.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
  - stylesheets/document.css
  - stylesheets/friends.css
  - stylesheets/file.css
  - stylesheets/article-cards.css
  - https://cdn.bootcdn.net/ajax/libs/lxgw-wenkai-screen-webfont/1.7.0/style.min.css #字体
  - https://static.zeoseven.com/zsft/92/main/result.css
  - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css # font-awesome表情支持


#[Navigation]
nav: 
  - 主页: index.md
  - 课程:
    - course/index.md
    - 程序设计与算法基础: course/fpa/final-exam-re.md
    - 数据结构基础: 
      - course/fds/index.md
      - 算法分析基础: course/fds/ch1.md
      - 线性数据结构: course/fds/ch2.md
      - 树: course/fds/ch3.md
      - 图: course/fds/ch4.md
      - 排序: course/fds/ch5.md
      - 散列: course/fds/ch6.md
    - 人工智能引论: 
      - course/ai/index.md
    - 高级数据结构与算法分析:
      - course/ads/index.md
      - AVL/Splay/摊还分析: course/ads/lec1.md
      - 红黑树/B+ 树: course/ads/lec2.md
      - 倒排索引: course/ads/lec3.md
      - 左式堆与斜堆: course/ads/lec4.md
      - 二项堆: course/ads/lec5.md
      - 回溯: course/ads/lec6.md
      - 分治法: course/ads/lec7.md
      - 动态规划: course/ads/lec8.md
      - 贪心算法: course/ads/lec9.md
      - NP: course/ads/lec10.md
      - 近似算法: course/ads/lec11.md
      - 局部搜索: course/ads/lec12.md
      - 随机算法: course/ads/lec13.md
    - 计算机体系结构:
      - course/arch/index.md
    - 编译原理:
      - course/comp/index.md
      - 词法分析: course/comp/ch2.md
      - 语法分析: course/comp/ch3.md
      - 抽象语法: course/comp/ch4.md
      - 语义分析: course/comp/ch5.md
      - 活动记录: course/comp/ch6.md
      - 中间代码: course/comp/ch7.md
      - 基本块划分: course/comp/ch8.md
      - 指令选择: course/comp/ch9.md
      - 活跃分析: course/comp/ch10.md
      - 寄存器分配: course/comp/ch11.md
  - 自学:
    - self/index.md
    - HTML 学习:
      - self/html/index.md
      - HTML 简介: self/html/lec1.md
      - 段落与基本格式: self/html/lec2.md
      - 其他格式: self/html/lec3.md
      - 其他元素: self/html/lec4.md
    - CSS 学习:
      - self/css/index.md
      - CSS 简介: self/css/lec1.md
      - 背景样式: self/css/lec2.md
    - Mkdocs 网页:
      - self/mkdocs/index.md
      - 简介与准备工作: self/mkdocs/ready.md
      - 本地构建网站: self/mkdocs/build.md
      - 部署到 gh-pages: self/mkdocs/deploy.md
      - 高级配置: self/mkdocs/advanced.md
      - 相关资源: self/mkdocs/resource.md
  - 友链: 
    - 友链: link/friends.md
    - 如何加入友链: link/join.md
  - 关于:
    - about/index.md
    - 彩蛋: about/tips.md